### ISSUE TITLE
Invalid Bundle Structure - The binary file 'Timepiece.framework/libswiftRemoteMirror.dylib' is not permitted

### ISSUE THREAD

**Issue by hdoria** [naoty/Timepiece#63] opened 2016-10-06 18:44 UTC
I'm using Timeline with Carthage. Now, when I try to upload my app to iTunes I get the following error:

Invalid Bundle Structure - The binary file 'MyApp.app/Frameworks/Timepiece.framework/libswiftRemoteMirror.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90206: "Invalid Bundle. The bundle at 'MyApp.app/Frameworks/Timepiece.framework' contains disallowed file 'Frameworks'."

**Comment by beartiago** [comment] 2016-10-28 12:27
same here...

**Comment by reidmain** [comment] 2016-11-03 17:20
This appears to be caused by the "Aways Embed Swift Standard Libraries" being set in the project.
![embed frameworks](https://cloud.githubusercontent.com/assets/535202/19976942/013863de-a1af-11e6-85b8-6b1a6f136c61.png)

It doesn't make sense for a Framework target to embed the Swift standard libraries. It is the responsibility of the App target to do that and they ensure that all of the Frameworks they are building against are the correct Swift version. Heck even if developers don't check this the compiler yells at them saying that a Framework was generated with a different version of Swift than the app.

**Comment by basememara** [comment] 2016-11-05 10:10
Serious issue, cannot submit app to the App Store. Please merge PR.

**Comment by naoty** [comment] 2016-11-05 12:36
@basememara Thank you for sending the PR!

I'm sorry... I merged the PR and released `1.0.1` just now.

**Closed by naoty** 2016-11-05 12:36 UTC

**Comment by basememara** [comment] 2016-11-05 20:39
Np, thx for taking the time to consider and the great lib 💯
